<a href="https://colab.research.google.com/github/jfaraudo/Python_examples/blob/main/Examples_Vector_and_Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Examples involving Vector and Matrix Algebra**

In [3]:
import numpy as np

**1) Vectors**

Vectors in numpy are introduced as arrays. They can be added and substracted. For example, let us add and substract the vectors (0,-2,0) and (1,0,0)

In [4]:
v = np.array([1,0,0])
print(v)
u = np.array([0,-2,0])
print(u)
w1 = u+v
print(w1)
w2=u-v
print(w2)


[1 0 0]
[ 0 -2  0]
[ 1 -2  0]
[-1 -2  0]


Dot product between u and v

In [5]:
np.dot(u,v)

0

Dot product between w1 and w2

In [ ]:
np.dot(w1,w2)

3

Cross (vector) product

In [ ]:
np.cross(v,u)

array([ 0,  0, -2])

**2) Matrix Algebra**

Let us define a matrix

In [ ]:
A=np.array([[2,2],[1,3]])
print(A)


[[2 2]
 [1 3]]


We can access to individual elements

In [ ]:
e = A[0,1]
print(e)

2


In [ ]:
f = A[1,1]
print(f)

3


or to full columns or lines to create vectors

In [ ]:
v=A[0,:]
print(v)

[2 2]


In [ ]:
u=A[:,0]
print(u)

[2 1]


We can also diagonalize the matrix (eigenvalues and eigenvectors)

In [ ]:
Valors,Vectors = np.linalg.eig(A)
print("Eigenvalues:",Valors)
print("EigenVectors:")
print(Vectors)

Eigenvalues: [1. 4.]
EigenVectors:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Test that the eigenvectors are truly eigenvectors.
First eigenvector:

In [ ]:
u=Vectors[:,0]
print(u)

[-0.89442719  0.4472136 ]


Apply the matrix to the vector

In [ ]:
np.dot(A,u)

array([-0.89442719,  0.4472136 ])

Same for the second eigenvector

In [ ]:
v=Vectors[0:,1]
print(v)

[-0.70710678 -0.70710678]


In [ ]:
np.dot(A,v)

array([-2.82842712, -2.82842712])

Some curious matrix

In [6]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.random.random([3,3])

array([[0.39650143, 0.2862621 , 0.79557747],
       [0.88220872, 0.94378837, 0.37141352],
       [0.79520949, 0.03658419, 0.87937976]])