<a href="https://colab.research.google.com/github/jfaraudo/Python_examples/blob/main/Examples_Vector_and_Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Examples involving Vector and Matrix Algebra**

In [1]:
import numpy as np

**1) Vectors**

Vectors in numpy are introduced as arrays. They can be added and substracted. For example, let us add and substract the vectors (0,-2,0) and (1,0,0)

In [2]:
v = np.array([1,0,0])
print(v)
u = np.array([0,-2,0])
print(u)
w1 = u+v
print(w1)
w2=u-v
print(w2)


[1 0 0]
[ 0 -2  0]
[ 1 -2  0]
[-1 -2  0]


Dot product between u and v

In [4]:
np.dot(u,v)

0

Dot product between w1 and w2

In [6]:
np.dot(w1,w2)

3

Cross (vector) product

In [7]:
np.cross(v,u)

array([ 0,  0, -2])

**2) Matrix Algebra**

Let us define a matrix

In [13]:
A=np.array([[2,2],[1,3]])
print(A)


[[2 2]
 [1 3]]


We can access to individual elements

In [17]:
e = A[0,1]
print(e)

2


In [16]:
f = A[1,1]
print(f)

3


or to full columns or lines to create vectors

In [20]:
v=A[0,:]
print(v)

[2 2]


In [19]:
u=A[:,0]
print(u)

[2 1]


We can also diagonalize the matrix (eigenvalues and eigenvectors)

In [24]:
Valors,Vectors = np.linalg.eig(A)
print("Eigenvalues:",Valors)
print("EigenVectors:")
print(Vectors)

Eigenvalues: [1. 4.]
EigenVectors:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Test that the eigenvectors are truly eigenvectors.
First eigenvector:

In [25]:
u=Vectors[:,0]
print(u)

[-0.89442719  0.4472136 ]


Apply the matrix to the vector

In [26]:
np.dot(A,u)

array([-0.89442719,  0.4472136 ])

Same for the second eigenvector

In [27]:
v=Vectors[0:,1]
print(v)

[-0.70710678 -0.70710678]


In [28]:
np.dot(A,v)

array([-2.82842712, -2.82842712])

Some curious matrix